image: python:2.7-wheezy
script:
  - virtualenv .
  - source bin/activate
  - pip install -r requirements.txt
  - python ./setup.py test
  - python ./setup.py sdist --formats gztar -q
notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: $$SLACK_CHANNEL
    on_started: true
    on_success: true
    on_failure: true
  webhook:
    urls:
      - $$GITTER_URL
    on_started: true
    on_success: true
    on_failure: true
