# vim: set ts=2 sts=2 sw=2:

---
build:
  image: python:$$PY_VERSION
  commands:
    - ( apt-get update && apt-get install -y git ) || ( apk update && apk add git bash )
    - pip install --upgrade virtualenv
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - pip install coveralls
    - nosetests --with-coverage
    - COVERALLS_REPO_TOKEN="$$COVERALLS_TOKEN" coveralls
    - python ./setup.py sdist --formats gztar -q

matrix:
  PY_VERSION:
    - 2.7-wheezy
    - 3.3-wheezy
    - 3.4-wheezy
    - 3.5-alpine

notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: $$SLACK_CHANNEL
    when:
      started: true
      success: true
      failure: true

publish:
  github_release:
    api_key: $$GITHUB_RELEASE_TOKEN
    files:
      - dist/*
    when:
      event: tag
      branch: master
