build:
  image: python:2.7-wheezy
  commands:
    - virtualenv .
    - source bin/activate
    - pip install -r requirements.txt
    - python ./setup.py test
    - python ./setup.py sdist --formats gztar -q

notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: $$SLACK_CHANNEL
    username: drone
    when:
      started: true
      success: true
      failure: true
  webhook:
    urls:
      - $$GITTER_URL
    when:
      started: true
      success: true
      failure: true
