build:
  image: python:$$PY_VERSION
  commands:
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - pip install pre-commit
    - pre-commit run --all-files
    - python ./setup.py test
    - python ./setup.py sdist --formats gztar -q

matrix:
  PY_VERSION:
    - 2.7-wheezy
    - 3.2-wheezy
    - 3.3-wheezy
    - 3.4-wheezy
    - 3.5-wheezy

notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: $$SLACK_CHANNEL
    when:
      started: true
      success: true
      failure: true

publish:
  github_release:
    api_key: $$GITHUB_RELEASE_TOKEN
    files:
      - dist/*
    when:
      event: tag
      branch: master
