# vim: set ts=2 sts=2 sw=2:

---
stages:
  - build-test
  - package
  - mirror
  - deploy

build-2.7:
  image: python:2.7-alpine
  stage: build-test
  script:
    - apk update && apk add git bash
    - pip install --upgrade virtualenv
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - nosetests --with-coverage

build-3.3:
  image: python:3.3-alpine
  stage: build-test
  script:
    - apk update && apk add git bash
    - pip install --upgrade virtualenv
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - nosetests --with-coverage

build-3.4:
  image: python:3.4-alpine
  stage: build-test
  script:
    - apk update && apk add git bash
    - pip install --upgrade virtualenv
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - nosetests --with-coverage

build-3.5:
  image: python:3.5-alpine
  stage: build-test
  script:
    - apk update && apk add git bash
    - pip install --upgrade virtualenv
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - nosetests --with-coverage

build-3.6:
  image: python:3.6-alpine
  stage: build-test
  script:
    - apk update && apk add git bash
    - pip install --upgrade virtualenv
    - virtualenv .
    - . bin/activate
    - pip install -r requirements.txt
    - nosetests --with-coverage

build-dists:
  image: python:alpine
  stage: package
  script:
    - apk update && apk add git bash
    - pip install --upgrade wheel
    - python ./setup.py sdist --formats gztar -q
    - python ./setup.py bdist_wheel -q
  artifacts:
    paths:
      - dist/

github:
  image: python:alpine
  stage: mirror
  script:
    - which ssh-agent || ( apk add openssh-client )
    - which git || ( apk add git )
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv || -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git remote add deploy git@github.com:maiome-development/malibu.git
    - git push deploy "$CI_COMMIT_REF_NAME"

dists:
  image: python:alpine
  stage: deploy
  script:
    - apk update && apk add git bash
    - pip install --upgrade wheel
    - echo "$PYPIRC" > ~/.pypirc
    - python ./setup.py sdist bdist_wheel upload -q
  only:
    - master

